package com.dtzhejiang.irs.res.bill.infra.mapper;

import com.dtzhejiang.irs.res.bill.infra.model.SubReport;
import com.dtzhejiang.irs.res.bill.infra.model.SubReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_report
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    int countByExample(SubReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_report
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    int deleteByExample(SubReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_report
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_report
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    int insert(SubReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_report
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    int insertSelective(SubReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_report
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    List<SubReport> selectByExample(SubReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_report
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    SubReport selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_report
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    int updateByExampleSelective(@Param("record") SubReport record, @Param("example") SubReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_report
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    int updateByExample(@Param("record") SubReport record, @Param("example") SubReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_report
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    int updateByPrimaryKeySelective(SubReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_report
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    int updateByPrimaryKey(SubReport record);
}