spring:
  datasource:
    url: jdbc:mysql://rm-vy2x7tev8h64905r4.mysql.rds.cloud-inner.zj.gov.cn:3306/irs-res-bill?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: irs_res_bill
    password: SM4[793fba22c58be0b357d18479ea727a7ba54e24449616549fef5f379c98f39ef8]
  redis:
    host: r-vy26ed4485bab654.redis.rds.cloud-inner.zj.gov.cn
    port: 6379
    password: SM4[216ee52010e61a7ec79d9af129357b52]
    timeout: 20000
    database: 1
    lettuce:
      pool:
        min-idle: 3
        max-active: 20
        max-idle: 10
        max-wait: 3000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

shiro:
  enabled: true

feign:
  userClientHost: http://59.202.44.203/cas
  appKey: irs-res-bill
  appSecret: YeBymaPcN4ctMmdNNevzr1U3dCmru296

workflow:
  api-url: http://59.202.44.203/flowable
  ak: FPsLrGMf
  sk: 216ec704cf27c229ecc0b9db9f45ba61
