spring:
  datasource:
    url: jdbc:mysql://rm-vy2x7tev8h64905r4.mysql.rds.cloud-inner.zj.gov.cn:3306/irs-res-bill?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: irs_res_bill
    password: SM4[793fba22c58be0b357d18479ea727a7ba54e24449616549fef5f379c98f39ef8]
  redis:
    host: r-vy26ed4485bab654.redis.rds.cloud-inner.zj.gov.cn
    port: 6379
    password: SM4[216ee52010e61a7ec79d9af129357b52]
    timeout: 20000
    database: 1
    lettuce:
      pool:
        min-idle: 3
        max-active: 20
        max-idle: 10
        max-wait: 3000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

shiro:
  enabled: true

forest:
  timeout: 10000

feign:
  userClientHost: http://59.202.44.203/flowablecas
  appKey: irs-res-bill
  appSecret: YeBymaPcN4ctMmdNNevzr1U3dCmru296

workflow:
  api-url: http://127.0.0.1:8080/flowable
  ak: FPsLrGMf
  sk: 216ec704cf27c229ecc0b9db9f45ba61

## 阿里云OSS
aliyun:
  oss:
    endpoint: http://oss-cn-hangzhou-zwynet-d01-a.internet.cloud.zj.gov.cn/
    access-key-id: wMhEw2BhpIDc1xwO
    access-key-secret: SM4[a8cfdb030ab93caaa7a5bc3325238391614ae9a4986b51b46978e6a30c0c7ff2]
    bucket-name: irs-yyyw
    file-folder: IRS-bill/
  net-oss:
    endpoint: https://oss-cn-hangzhou-zwynet-d01-a.internet.cloud.zj.gov.cn/
    pubKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKs/JBGzwUB2aVht4crBx3oIPBLNsjGsC0fTXv+nvlmklvkcolvpvXLTjaxUHR3W9LXxQ2EHXAJfCB+6H2YF1k8CAwEAAQ==
    access-key-id: wMhEw2BhpIDc1xwO
    access-key-secret: SM4[a8cfdb030ab93caaa7a5bc3325238391614ae9a4986b51b46978e6a30c0c7ff2]
    bucket-name: irs-yyyw
    file-folder: IRS-bill/
    callback-url: http://formtest.irs.zj.gov.cn/gdAdapter/fileApi/callBack/
    tmp-dir: tmp/
  order:
    ak: LTAI5tLZwMokv4U9MJg9yZDr
    sk: SM4[467003415a19abc18b138d8705d09004f4766c9f9573b0861b69b0c9da7b81fe]
    endpoint: workorder.aliyuncs.com
    proxy: http://10.145.8.119:8090
