spring:
  datasource:
    url: jdbc:mysql://59.202.48.91:3336/irs-res-bill?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: irs_res_bill
    password: 40ES9k1mT8IrLzl^ov%g
  redis:
    host: 59.202.48.91
    port: 6379
    password: Da(#Hfl0Sy
    timeout: 20000
    database: 1
    lettuce:
      pool:
        min-idle: 3
        max-active: 20
        max-idle: 10
        max-wait: 3000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


workflow:
  api-url: http://59.202.44.203/flowable
  ak: FPsLrGMf
  sk: 216ec704cf27c229ecc0b9db9f45ba61

shiro:
  enabled: true

forest:
  timeout: 10000

feign:
  userClientHost: http://59.202.44.203/flowablecas
  appKey: irs-res-bill
  appSecret: YeBymaPcN4ctMmdNNevzr1U3dCmru296
