spring:
  datasource:
    url: jdbc:mysql://59.202.48.91:3336/irs-res-bill?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: irs_res_bill
    password: 40ES9k1mT8IrLzl^ov%g
  redis:
    host: 59.202.48.91
    port: 6379
    password: Da(#Hfl0Sy
    timeout: 20000
    database: 1
    lettuce:
      pool:
        min-idle: 3
        max-active: 20
        max-idle: 10
        max-wait: 3000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


workflow:
  api-url: http://59.202.44.203/flowable
  ak: FPsLrGMf
  sk: 216ec704cf27c229ecc0b9db9f45ba61

shiro:
  enabled: true

forest:
  timeout: 10000

feign:
  userClientHost: http://59.202.44.203/flowablecas
  appKey: irs-res-bill
  appSecret: YeBymaPcN4ctMmdNNevzr1U3dCmru296

## 阿里云OSS
aliyun:
  oss:
    endpoint: http://oss-cn-hangzhou-zwynet-d01-a.internet.cloud.zj.gov.cn/
    access-key-id: wMhEw2BhpIDc1xwO
    access-key-secret: SM4[a8cfdb030ab93caaa7a5bc3325238391614ae9a4986b51b46978e6a30c0c7ff2]
    bucket-name: irs-yyyw
    file-folder: IRS-net-gd/
  net-oss:
    endpoint: https://oss-cn-hangzhou-zwynet-d01-a.internet.cloud.zj.gov.cn/
    pubKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKs/JBGzwUB2aVht4crBx3oIPBLNsjGsC0fTXv+nvlmklvkcolvpvXLTjaxUHR3W9LXxQ2EHXAJfCB+6H2YF1k8CAwEAAQ==
    access-key-id: wMhEw2BhpIDc1xwO
    access-key-secret: SM4[a8cfdb030ab93caaa7a5bc3325238391614ae9a4986b51b46978e6a30c0c7ff2]
    bucket-name: irs-yyyw
    file-folder: IRS-net-gd/
    callback-url: http://formtest.irs.zj.gov.cn/gdAdapter/fileApi/callBack/
    tmp-dir: tmp/
  order:
    ak: LTAI5tLZwMokv4U9MJg9yZDr
    sk: SM4[467003415a19abc18b138d8705d09004f4766c9f9573b0861b69b0c9da7b81fe]
    endpoint: workorder.aliyuncs.com
    proxy: http://10.145.8.119:8090
