spring:
  datasource:
    url: jdbc:mysql://59.202.48.91:3336/irs-res-bill?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: irs_res_bill
    password: SM4[793fba22c58be0b357d18479ea727a7ba54e24449616549fef5f379c98f39ef8]
  redis:
    host: 59.202.48.91
    port: 6379
    password: SM4[216ee52010e61a7ec79d9af129357b52]
    timeout: 20000
    database: 1
    lettuce:
      pool:
        min-idle: 3
        max-active: 20
        max-idle: 10
        max-wait: 3000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


workflow:
  api-url: http://59.202.44.203/flowable
  ak: FPsLrGMf
  sk: 216ec704cf27c229ecc0b9db9f45ba61
