spring:
  datasource:
    url: jdbc:mysql://{ip}:{port}/{db}?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username:
    password:
  redis:
    host:
    port:
    password:
    timeout: 20000
    database: 1
    lettuce:
      pool:
        min-idle: 3
        max-active: 20
        max-idle: 10
        max-wait: 3000
