spring:
  datasource:
    url: jdbc:mysql://rm-vy2opkp6nf0208y31.mysql.rds.cloud-inner.zj.gov.cn:3306/irs-res-bill?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: irs_res_bill
    password: SM4[01cc88713373ff418ae2d997c0074b8c5e316eb85405ef3d89531afae112f312]
  redis:
    host: 59.202.48.91
    port: 6379
    password: SM4[216ee52010e61a7ec79d9af129357b52]
    timeout: 20000
    database: 8
    lettuce:
      pool:
        min-idle: 3
        max-active: 20
        max-idle: 10
        max-wait: 3000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


workflow:
  api-url: http://59.202.44.204/flowable
  ak: fxn5oNYX
  sk: 9066746a00b0fb0ce16a935413684a2a
