package com.dtzhejiang.irs.res.bill.infra.model;

import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Getter;
import lombok.Setter;

import java.util.Date;
@Getter
@Setter
@TableName(value = "sub_report",autoResultMap = true)
public class SubReport extends BaseDO{


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_report.name
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_report.sub_type
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    private Long subType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_report.operation_indices
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    private String operationIndices;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_report.operation_data
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    private String operationData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_report.normal_value
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    private String normalValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_report.operation_results
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    private String operationResults;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_report.operation_results_status
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    private String operationResultsStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_report.sub_status
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    private String subStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_report.remark
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_report.approval_id
     *
     * @mbggenerated Thu Feb 23 10:59:50 CST 2023
     */
    private String approvalId;


}